version: "3"
services:
#  db:
#    image: mysql:5.7
#    environment:
#      MYSQL_ROOT_PASSWORD: LuwCDE97zppvQhzP
#      MYSQL_DATABASE: asvoting
#      MYSQL_USER: asvoting
#      MYSQL_PASSWORD: D9cACV8Pue3CvM93
#    networks:
#      default_network:
#    volumes:
#      - ./containers/mysql/config/my.cnf:/etc/mysql/my.cnf
#      - ./data/mysql:/var/lib/mysql
#      - ./data/mysql_import:/docker-entrypoint-initdb.d
#  installer:
#    build: containers/installer
#    environment:
#      - COMPOSER_CACHE_DIR=/var/app/var/cache/composer
#      - COMPOSER_ALLOW_SUPERUSER=1
#    networks:
#      default_network:
#    depends_on:
#      - db
#      - redis
#    volumes:
#      - .:/var/app
  npm:
    build: containers/npm
    ports:
      - 8888:8888
    volumes:
      - .:/var/app
#  php_fpm:
#    build: containers/php_fpm
#    image: voting_php_fpm
#    environment:
#      - COMPOSER_CACHE_DIR=/var/app/var/cache/composer
#      - COMPOSER_ALLOW_SUPERUSER=1
#    depends_on:
#      - db
#      - redis
#    networks:
#      default_network:
#    volumes:
#      - .:/var/app
#  php_fpm_debug:
#    build: containers/php_fpm_debug
#    environment:
#      - COMPOSER_CACHE_DIR=/var/app/var/cache/composer
#      - COMPOSER_ALLOW_SUPERUSER=1
#    depends_on:
#      - redis
#      - php_fpm
#    networks:
#      default_network:
#    volumes:
#      - .:/var/app
#  redis:
#    image: redis:4.0.6
#    volumes:
#      - .:/var/app
#    command: ["redis-server", "/var/app/containers/redis/config/redis.conf"]
#    networks:
#      default_network:
#  nginx:
#    build: containers/nginx
#    depends_on:
#      - db
#      - redis
#      - php_fpm
#    volumes:
#      - .:/var/app
#    networks:
#      default_network:
#        aliases:
#          - internal.opensourcefees.com
#  supervisord:
#    build: containers/supervisord
#    depends_on:
#      - redis
#    volumes:
#      - .:/var/app
#  varnish:
#    build: containers/varnish
#    environment:
#      CACHE_SIZE: 128m
#    networks:
#      default_network:
#    volumes:
#      - ./:/var/app
#    depends_on:
#      - db
#      - nginx
#      - php_fpm
#      - redis
networks:
  default_network:

